In [1]:
import numpy as np
a = np.array([[2,0,1],
              [-1,3,1],
              [0,1,0]])

In [2]:
a[,:]

SyntaxError: invalid syntax (<ipython-input-2-fb58cd23ef9f>, line 1)

In [44]:
print(a)

[[ 2  0  1]
 [-1  3  1]
 [ 0  1  0]]


In [45]:
print(a[1][1])

3


In [46]:
np.linalg.det(a)

-2.9999999999999996

In [63]:
ttt = list(range(10))
cc = 5
list(range(cc))+list(range(cc+1, len(ttt)))

[0, 1, 2, 3, 4, 6, 7, 8, 9]

In [4]:
def determinant_of_matrix(a):
    ans = 0.
    indices = list(range(len(a))) #list of indexes
    if len(a) == 2 and len(a[0]) == 2:
        val = a[0][0] * a[1][1] - a[1][0] * a[0][1] #determinant of 2x2 matrix
        return val
    for cc in indices: # finding alg_adition for each curent column
        ac = np.copy(a) # making a copy of matrix
        ac = np.delete(ac, (0), axis = 0) #removing first row
        ac = np.delete(ac, (cc), axis = 1) #removing iteral column
        sign = (-1) ** (cc % 2) # sign of -1 
        unter_det = determinant_of_matrix(ac)
        ans += sign * a[0][cc] * unter_det 
    return ans

In [68]:
def determinant_of_matrix(a):
    ans = 0.
    if len(a) == 2 and len(a[0]) == 2:
        return a[0][0] * a[1][1] - a[1][0] * a[0][1] #determinant of 2x2 matrix
    for cc in range(len(a)): # finding alg_adition for each curent column
        columns = list(range(cc))+list(range(cc+1, len(a)))
        unter_det = determinant_of_matrix(a[1:,columns])
        sign = (-1) ** (cc % 2) # sign of -1 
        ans += sign * a[0][cc] * unter_det 
    return ans

In [69]:
determinant_of_matrix(a)

-3.0

In [70]:
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [71]:
determinant_of_matrix(b)

0.0

In [51]:
c = np.array([[1.5,2,3],
              [4,5,6.3],
              [7,8,9]])
determinant_of_matrix(c)

-0.899999999999995

In [74]:
%%timeit
d = np.array([[1,2,3,7],
              [4,5,6,3],
              [7,8,9,8],
              [2,1,6,8]])
determinant_of_matrix(d)

223 µs ± 16.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [75]:
%%timeit
np.linalg.det(d)

12.7 µs ± 249 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [86]:
e = np.random.randn(1000,1000)

In [85]:
np.linalg.det()

(100, 100)

In [5]:
q = np.array([[6,-5,-3],
              [3,-2,-2],
              [2,-2,0]])
determinant_of_matrix(q)

2.0