In [12]:
import numpy as np
a = np.array([[2,1,3,9],
              [1,-2,1,-2],
              [3,2,2,7]])

In [13]:
def determinant_of_matrix(a):
    ans = 0.
    indices = list(range(len(a))) #list of indexes
    if len(a) == 2 and len(a[0]) == 2:
        val = a[0][0] * a[1][1] - a[1][0] * a[0][1] #determinant of 2x2 matrix
        return val
    for cc in indices: # finding alg_adition for each curent column
        ac = np.copy(a) # making a copy of matrix
        ac = np.delete(ac, (0), axis = 0) #removing first row
        ac = np.delete(ac, (cc), axis = 1) #removing iteral column
        sign = (-1) ** (cc % 2) # sign of -1 
        unter_det = determinant_of_matrix(ac)
        ans += sign * a[0][cc] * unter_det 
    return ans

In [90]:
def lin_eq(a):
    ans = 0
    dmain = np.copy(a) 
    n = len(dmain)
    d = a[:, n] #column of equationsresults
    dmain = np.delete(dmain, (n), axis = 1) #matrix without column of answers
    indices = list(range(n))#list of indexes
    for ac in indices: # finding upper determinant for each curent column
        cm = np.copy(dmain) # making a copy of matrix
        cm = np.delete(cm, (ac), axis = 1) # deliting column where index same as var index 
        cm = np.insert(cm, (ac),d, axis = 1) # adding in that place column of equations results
        ans = determinant_of_matrix(cm)/determinant_of_matrix(dmain) #finding answer for each variable
        print('x',ac+1,'=',ans)

In [96]:
lin_eq(a)

x 1 = -1.0
x 2 = 2.0
x 3 = 3.0


In [97]:
a1 = np.array([[2,1,3],
              [1,-2,1],
              [3,2,2]])
a2 = np.array([9,-2,7])
np.linalg.solve(a1, a2)

array([-1.,  2.,  3.])

In [98]:
b = np.array([[1,-1,3,1,5],
              [4,-1,5,4,4],
              [2,-2,4,1,6],
              [1,-4,5,-1,3]])
lin_eq(b)

x 1 = 9.0
x 2 = 18.0
x 3 = 10.0
x 4 = -16.0


In [99]:
b1 = np.array([[1,-1,3,1],
              [4,-1,5,4],
              [2,-2,4,1],
              [1,-4,5,-1]])
b2 = np.array([5, 4,6, 3])
np.linalg.solve(b1, b2)

array([  9.,  18.,  10., -16.])

In [100]:
d = a[:, 3]
print(d)
cm = np.copy(a) # making a copy of matrix
cm = np.delete(cm, (1), axis = 1)
cm = np.insert(cm, (1), d, axis = 1)
print(cm)

[ 9 -2  7]
[[ 2  9  3  9]
 [ 1 -2  1 -2]
 [ 3  7  2  7]]


In [106]:
!pwd && ls *.ipynb

/home/dan
 Determinant.ipynb		  'Reverse matrix.ipynb'   Untitled3.ipynb
'linear equations complex.ipynb'   Untitled1.ipynb	   Untitled.ipynb
'linear equations solver.ipynb'    Untitled2.ipynb


In [119]:
!ls -l

total 148
drwxr-xr-x 26 dan dan  4096 июл 11  2019  anaconda2
drwxr-xr-x  2 dan dan  4096 июл  8  2019  Desktop
-rw-r--r--  1 dan dan  7096 апр 26 12:17  Determinant.ipynb
drwxr-xr-x  3 dan dan  4096 апр 22 20:35  dockers
drwxr-xr-x  2 dan dan  4096 июл  8  2019  Documents
drwxr-xr-x  3 dan dan  4096 июл 12  2019  Downloads
-rw-r--r--  1 dan dan   182 июл 12  2019  flex_file.txt
-rw-r--r--  1 dan dan  5017 апр 26 11:13 'linear equations complex.ipynb'
-rw-r--r--  1 dan dan  7564 апр 26 12:51 'linear equations solver.ipynb'
drwxr-xr-x  2 dan dan  4096 июл  8  2019  Music
drwxr-xr-x  8 dan dan  4096 апр 26 12:16  Nextcloud
drwxr-xr-x  2 dan dan  4096 апр 22 20:24  pg
drwxr-xr-x  2 dan dan  4096 июл  8  2019  Pictures
drwxr-xr-x  2 dan dan  4096 апр 26 12:34  prjects
drwxr-xr-x  2 dan dan  4096 апр 26 12:49  projects
drwxr-xr-x  2 dan dan  4096 июл  8  2019  Public
-rw-r--r--  1 dan dan  3580 апр 26 12:33 'Reverse matrix.ipynb'
drwxr-xr-x  2 dan dan  4096 июл  8  2019  Templates
-rw-r--r-

In [ ]:
!prjects/

In [118]:
!ls prjects

In [112]:
!mv Linear\ Algebra\ methods prjects/