In [223]:
import numpy as np
a = np.array([[2.,1.,3.,9.],
              [1.,-2.,1.,-2.],
              [3.,2.,2.,7.]], dtype = np.float)

In [224]:
a.astype(int)

array([[ 2,  1,  3,  9],
       [ 1, -2,  1, -2],
       [ 3,  2,  2,  7]])

In [225]:
def lin_eq(a):
    """
    Gaus method of solving linear equations.
    
    this function solves systems of linear equations by using Thom Yves' Gaus interpretation
    
    input: numpy float matrix 
        |ex:lin_eq(numpy_float_matrix)
    
    output: numpy float matrix
    
    variables:
        |dmain - matrix of coefficients
        |d     - matrix of constant terms/answers after all transformations
        |cdsc  - scalar of current main diagonal element [Current Diagonal SCalar]
        |sc    - scalar of row thith current main diagonal element
        |n     - length of coefficient matrix
        |cd    - index of current main diagonal element
        |i     - index of rows that are not row with current main diagonal element 
    
    """
    cdsc = 1. # scalar of current main diagonal element [Current Diagonal SCalar]
    dmain = np.copy(a) #copy of matrix
    n = len(dmain) # length of coefficient matrix
    d = np.copy(a[:, n]) #column of constant terms
    dmain = np.delete(dmain, n, axis = 1) #making dmain a coefficient matrix
    for cd in range(n): # index of current diagonal element
        cdsc = 1. / dmain[cd][cd] # scalar for element of main diagonal
        dmain[cd,:] *= cdsc # scaling row and making diagonal element equal 1
        d[cd] *= cdsc # scaling constant terms
        for i in range(n): # making 0 in column of current diagonal element by summing rows
            if i == cd: continue # skipping cd row
            sc = dmain[i][cd] # scalar for cd row for substracting
            dmain[i] = dmain[i] - sc * dmain[cd] # substructing and making 0 in column with current diagonal element
            d[i] = d[i] - sc * d[cd] # making same transformations with ans
    return(d)

In [226]:
a

array([[ 2.,  1.,  3.,  9.],
       [ 1., -2.,  1., -2.],
       [ 3.,  2.,  2.,  7.]])

In [228]:
lin_eq(a)

array([-1.,  2.,  3.])

In [229]:
b = np.array([[1.,-1.,3.,1.,5.],
              [4.,-1.,5.,4.,4.],
              [2.,-2.,4.,1.,6.],
              [1.,-4.,5.,-1.,3.]])
lin_eq(b)

array([  9.,  18.,  10., -16.])

In [238]:
lin_eq(b)

array([  9.,  18.,  10., -16.])